create table
  public.fridge (
    fridge_id bigint generated by default as identity,
    ingredient_id bigint not null,
    quantity bigint null,
    constraint fridge_pkey primary key (fridge_id, ingredient_id),
    constraint fridge_fridge_id_key unique (fridge_id),
    constraint fridge_ingredient_id_fkey foreign key (ingredient_id) references ingredient (ingredient_id)
  ) tablespace pg_default;

create table
  public.ingredient (
    ingredient_id bigint generated by default as identity,
    name text not null,
    vegan boolean null,
    vegetarian boolean null,
    paleo boolean null,
    calories bigint null,
    protein bigint null,
    carbs bigint null,
    fat bigint null,
    aisle text null,
    quantity text null,
    constraint ingredient_pkey primary key (ingredient_id)
  ) tablespace pg_default;

create table
  public.recipe (
    recipe_id bigint generated by default as identity,
    sku text not null,
    name text null,
    protein bigint null,
    calories bigint null,
    vegan boolean null,
    vegetarian boolean null,
    paleo boolean null,
    country_origin text null,
    meal_type text null,
    carbs bigint null,
    servings integer null,
    time_to_make integer null,
    steps text null,
    constraint recipe_pkey primary key (recipe_id)
  ) tablespace pg_default;

create table
  public.recipe_ingredients (
    recipe_id bigint generated by default as identity,
    ingredient_id bigint not null,
    quantity real null,
    constraint recipe_ingredients_pkey primary key (recipe_id, ingredient_id),
    constraint recipe_ingredients_ingredient_id_fkey foreign key (ingredient_id) references ingredient (ingredient_id),
    constraint recipe_ingredients_recipe_id_fkey foreign key (recipe_id) references recipe (recipe_id)
  ) tablespace pg_default;

create table
  public.shopping_list (
    shop_list_id bigint generated by default as identity,
    ingredient_id bigint not null,
    measurement text null,
    purchase boolean null,
    constraint shopping_list_pkey primary key (shop_list_id),
    constraint shopping_list_ingredient_id_fkey foreign key (ingredient_id) references ingredient (ingredient_id)
  ) tablespace pg_default;

create table
  public.user (
    user_id bigint generated by default as identity,
    name text not null,
    fridge_id bigint null,
    shop_list_id bigint null,
    email text null,
    phone text null,
    constraint user_pkey primary key (user_id),
    constraint user_fridge_id_key unique (fridge_id),
    constraint user_fridge_id_fkey foreign key (fridge_id) references fridge (fridge_id),
    constraint user_shop_list_id_fkey foreign key (shop_list_id) references shopping_list (shop_list_id)
  ) tablespace pg_default;

INSERT INTO recipes (recipe_id, sku, name, protein, calories, vegan, vegetarian, paleo, country_origin, meal_type, carbs, servings, time_to_make, steps)
VALUES (1, 'SHRIMP_FRIED_CAULIFLOWER_RICE_0', 'shrimp fried cauliflower rice', 28, 295, FALSE, FALSE, TRUE, 'china', 'dinner', 9, 4, 25, "1. Have all ingredients prepped and ready to go before beginning. 2. In a bowl, toss the shrimp with the tapioca or arrowroot, salt and pepper. Heat a large nonstick skillet over medium high heat. Once hot, add 1 Tbsp avocado oil or ghee. Add shrimp in a single layer and cook 1-2 minutes per side until opaque, careful not to overcook. Remove to a plate and turn the heat to medium. 3. With the skillet over medium heat, add the whisked eggs and cook until just set, breaking them up with your spatula. Set them aside with the shrimp. 4. Add the second tablespoon of oil or ghee to the skillet and adjust heat medium high. Add the diced carrots and cook, stirring, 3-4 minutes or until fork tender. Then add in the white part of the scallions, ginger, and garlic and stir to combine. Cook another minute until fragrant. 5. Add in the cauliflower rice, coconut aminos and sesame oil and stir to combine. Cook about 2-3 minutes to soften the cauliflower rice. Add in the shrimp and eggs and stir and cook 30-60 seconds to heat through, then remove from heat. Garnish with the green part of the scallions and additional coconut aminos or salt and pepper to taste. Serve right away. Leftovers can be saved in the sealed container in the refrigerator for up to 4 days. Enjoy!");

INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity)
VALUES
    (1, 1, 2.67),
    (1, 2, 0.33),
    (1, 3, 3),
    (1, 4, 1.5),
    (1, 5, 1),
    (1, 6, 2),
    (1, 7, 3),
    (1, 8, 1.5),
    (1, 9, 4),
    (1, 10, 1),
    (1, 11, 1),
    (1, 12, 1);

INSERT INTO ingredients (ingredient_id, name, vegan, vegetarian, paleo, calories, protein, carbs, fat, aisle, quantity)
VALUES
    (6, 'ginger', TRUE, TRUE, TRUE, 2, 0, 0, 0, 'produce', '1 tsp'),
    (5, 'scallion', TRUE, TRUE, TRUE, 32, 2, 7, 0, 'produce', '1 cup'),
    (2, 'avocado oil', TRUE, TRUE, TRUE, 124, 0, 0, 14, 'cooking oils', '1 tbsp'),
    (4, 'carrot', TRUE, TRUE, TRUE, 50, 1, 12, 0, 'produce', '1 cup'),
    (3, 'egg', FALSE, TRUE, TRUE, 78, 6, 1, 5, 'dairy', '1 egg'),
    (8, 'cauliflower rice', TRUE, TRUE, TRUE, 25, 2, 5, 0, 'produce', '1 cup'),
    (9, 'coconut aminos', TRUE, TRUE, TRUE, 12, 0, 3, 0, 'condiments', '1 tbsp'),
    (10, 'sesame oil', TRUE, TRUE, TRUE, 120, 0, 0, 14, 'cooking oil', '1 tbsp'),
    (1, 'shrimp', FALSE, FALSE, TRUE, 101, 19, 1, 1, 'seafood', '3 oz'),
    (7, 'garlic', TRUE, TRUE, TRUE, 5, 0, 1, 0, 'produce', '1 clove'),
    (11, 'salt', TRUE, TRUE, TRUE, 0, 0, 0, 0, 'seasonings', '1 tsp'),
    (12, 'pepper', TRUE, TRUE, TRUE, 6, 0, 2, 0, 'seasonings', '1 tsp'),
    (13, 'steak', FALSE, FALSE, TRUE, 179, 26, 0, 8, 'meat', '3 oz'),
    (14, 'crushed red pepper flakes', TRUE, TRUE, TRUE, 6, 0, 1, 0, 'seasonings', '1 tsp'),
    (16, 'fresh parsley', TRUE, TRUE, TRUE, 1, 0, 0, 0, 'produce', '1 tbsp'),
    (15, 'unsalted butter', FALSE, TRUE, TRUE, 102, 0, 0, 12, 'dairy', '1 tbsp'),
    (17, 'salted butter', FALSE, TRUE, TRUE, 102, 0, 0, 12, 'dairy', '1 tbsp'),
    (18, 'white granulated sugar', TRUE, TRUE, FALSE, 392, 0, 104, 0, 'seasonings', '0.5 cup'),
    (19, 'light brown sugar', TRUE, TRUE, FALSE, 264, 0, 70, 0, 'seasonings', '0.5 cup'),
    (20, 'vanilla extract', TRUE, TRUE, FALSE, 12, 0, 1, 0, 'seasonings', '1 tsp'),
    (21, 'all-purpose flour', TRUE, TRUE, FALSE, 455, 13, 95, 1, 'baking', '1 cup'),
    (22, 'baking soda', TRUE, TRUE, TRUE, 0, 0, 0, 0, 'baking', '1 tsp'),
    (23, 'baking powder', TRUE, TRUE, FALSE, 5, 0, 2, 0, 'baking', '1 tsp'),
    (24, 'semisweet chocolate chips', FALSE, TRUE, FALSE, 404, 4, 54, 26, 'baking', '0.5 cup');
